defaults:
  - config
  - override data: vqav2
  - override model: llava
  - override evaluation: full
  - _self_
fed:
  mode: lora_llm
  lr: 0.0001
attack:
  iterations: 1000
  max_evaluations: 1600
  text_method: lamp_adapted
  prior_model: openai-community/gpt2
  prior_revision: 607a30d783dfa663caf39e06633721c8d4cfcd7e
